// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrNkW4JV8L-b8kxu_bazcYVNSz-QEc7Xk',
    appId: '1:1021969266142:web:1669fd62b5f411796a994f',
    messagingSenderId: '1021969266142',
    projectId: 'archivey-4d62f',
    authDomain: 'archivey-4d62f.firebaseapp.com',
    storageBucket: 'archivey-4d62f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBAOqop8X8LdXhQaFCkYPKNUVphecJJw',
    appId: '1:1021969266142:android:2ea765d367c5a7ac6a994f',
    messagingSenderId: '1021969266142',
    projectId: 'archivey-4d62f',
    storageBucket: 'archivey-4d62f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBEvbX5mDBR87YczhKQpfBp5X5SNhNjwE',
    appId: '1:1021969266142:ios:7d8a2f068c386dae6a994f',
    messagingSenderId: '1021969266142',
    projectId: 'archivey-4d62f',
    storageBucket: 'archivey-4d62f.firebasestorage.app',
    iosBundleId: 'com.archivey.archivey',
  );

}